#name of the workflow
name: Build and Deploy Spring app
#on is an action
on:
  push:
    branches:
      -main
permissions:
  contents: read
  id-token: write
  pull-requests: write
  security-events: write
  actions: read
jobs:
  build-deploy:
    name: Build and deploy spring boot for beginners
    #runners predefined by github where you want to run your project
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: unit tests
        run : mvn -B test --file pom.xml
      - name: build the application
      #writing multiple commands
        # run: |
        #   mvn clean 
        #   mvn -B package --file pom.xml
      # #update dependency graph
      # - name: Update dependency graph
      #   uses: advanced-security/maven-dependency-submission-action@v4